# CS5494 Final Project — Restaurant Review Rating

本 Notebook 按照实验流程逐步完成三条评分路线：

| Task | 方法 | 说明 |
|------|------|------|
| **A** | Zero-shot | 直接用基础模型推理 |
| **B.1.1** | N-shot ICL | 给模型提供少量示例后推理 |
| **B.1.2** | LoRA 微调 | 指令微调后推理 |

**运行前请确认**：
- 已执行 `pip install -r requirements.txt`
- `data/` 目录下包含 `review_train.csv`、`review_test.csv`、`test_answer.csv`
- （可选）如需从 ModelScope 下载模型，请设置 `USE_MODELSCOPE = True`

---
## 0. 全局配置

所有超参数、路径、开关统一在此 cell 设置，后续 cell 均使用这里的变量。

In [6]:
import sys, os
# notebook 在 notebooks/ 子目录，把项目根目录加入 Python 路径
sys.path.insert(0, os.path.abspath(os.path.join(os.getcwd(), '..')))

MODEL_NAME      = "Qwen/Qwen2.5-0.5B-Instruct"
# MODEL_NAME      = "Qwen/Qwen2.5-1.5B-Instruct"
# MODEL_NAME      = "Qwen/Qwen2.5-3B-Instruct"
USE_MODELSCOPE  = True                            # True = ModelScope 镜像下载
MODEL_CACHE_DIR = "../models"

DATA_DIR        = "../data"
SEED            = 5494

DEBUG_TRAIN_SIZE = None
DEBUG_TEST_SIZE  = None

N_SHOT          = 4        # few-shot 示例数
N_PER_RATING    = 10       # 每个评分从训练集中收集多少个示例

LORA_CHECKPOINT_DIR = "../qwen_lora_checkpoints"
LORA_FINAL_DIR      = "../qwen_lora_final"

MAX_NEW_TOKENS  = 10       # 推理时最多生成 token 数

model_short_name  = MODEL_NAME.split('/')[-1]
OUTPUT_DIR      = f"../outputs/temp/{model_short_name}"
os.makedirs(OUTPUT_DIR, exist_ok=True)
print(f"配置完成 ✓ (结果将保存在 {OUTPUT_DIR})")

配置完成 ✓ (结果将保存在 ../outputs/temp/Qwen2.5-0.5B-Instruct)

---
## 1. 数据加载

`load_project_data` 会自动读取三份 CSV 并将文本评分（如 `"4 star"`）转换为数值列 `rating_numeric`（1-5）。

In [7]:
from dataset import load_project_data

train_df, test_df, answer_df = load_project_data(DATA_DIR)

print(f"训练集: {len(train_df)} 条")
print(f"测试集: {len(test_df)} 条")
print(f"答案集: {len(answer_df)} 条")
train_df.head(3)

训练集: 9067 条
测试集: 1007 条
答案集: 1007 条

,Review_id,Author,Title,Review,Rating,Dates,Restaurant,Location,Category,rating_numeric
0,4091810389,Choi Yee C,no table,"nice place to visit everytime go melaka, not s...",4 star,Reviewed 14 June 2016,Jonker 86 QQ Ice,Melaka,Italian,4
1,8163808786,Renganathan S,Best food in town,I tried linguine bolognaise sauce... It's very...,5 star,Reviewed 13 September 2013,Gianni's Trattoria,JB,Italian,5
2,6466234202,"vidyamenonKuala Lumpur, Malaysia",Was in the area...,Was around the area and stopped by to have a d...,4 star,Reviewed 14 April 2018,One Serambi Cafe,Shah Alam,Mediterranean,4

### 1.1 标签分布

查看训练集各评分类别的样本数，确认数据是否均衡。

In [8]:
print("训练集评分分布:")
print(train_df["rating_numeric"].value_counts().sort_index())
print()
print("答案集评分分布:")
print(answer_df["rating_numeric"].value_counts().sort_index())

训练集评分分布:
rating_numeric
1    1817
2    1951
3    1739
4    1785
5    1775
Name: count, dtype: int64

答案集评分分布:
rating_numeric
1    212
2    223
3    213
4    169
5    190
Name: count, dtype: int64

---
## 2. 划分训练集 / 验证集

使用分层切分（stratify）保证各评分类别在训练集和验证集中比例一致。

- `test_size=0.2`：20% 作为验证集
- `debug_sample_size`：设置后会对切分结果进行随机截断，用于快速调试

In [9]:
from dataset import split_train_val

train_split, val_split = split_train_val(
    train_df,
    seed=SEED,
    test_size=0.2,
    debug_sample_size=DEBUG_TRAIN_SIZE,
)

print(f"训练子集: {len(train_split)} 条")
print(f"验证子集: {len(val_split)} 条")

训练子集: 7253 条
验证子集: 1814 条

### 调试用：截断测试集

推理很慢时，可以先在小样本上验证流程。

In [10]:
if DEBUG_TEST_SIZE is not None:
    test_df  = test_df.sample(n=min(DEBUG_TEST_SIZE, len(test_df)), random_state=SEED).reset_index(drop=True)
    answer_df = answer_df[answer_df["Review_id"].isin(test_df["Review_id"])].reset_index(drop=True)
    print(f"调试模式：测试集截断为 {len(test_df)} 条")
else:
    print(f"全量测试集：{len(test_df)} 条")

全量测试集：1007 条

---
## 3. 加载基础模型

`load_tokenizer_and_model` 会自动检测设备（CUDA / NPU / MPS / CPU）并选择合适的 dtype。

返回值：
- `tokenizer`：分词器
- `base_model`：未微调的基础模型
- `model_path`：实际加载路径
- `device`：`DeviceInfo` 对象，含设备类型和显存信息

In [11]:
from model import load_tokenizer_and_model

tokenizer, base_model, model_path, device = load_tokenizer_and_model(
    model_name=MODEL_NAME,
    use_modelscope=USE_MODELSCOPE,
    cache_dir=MODEL_CACHE_DIR,
)

print(f"设备类型 : {device.device_type}")
print(f"设备名称 : {device.device_name}")
if device.total_memory_gb:
    print(f"显存容量 : {device.total_memory_gb:.1f} GB")
print(f"模型路径 : {model_path}")

d:\anaconda3\condaData\envs_dirs\qwen_lora\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

本地缓存命中，跳过下载: ..\models\Qwen\Qwen2.5-0.5B-Instruct

`torch_dtype` is deprecated! Use `dtype` instead!
Loading weights: 100%|██████████| 290/290 [00:00<00:00, 2059.10it/s]

设备类型 : cuda
设备名称 : NVIDIA GeForce RTX 5060 Laptop GPU
显存容量 : 8.5 GB
模型路径 : ..\models\Qwen\Qwen2.5-0.5B-Instruct

---
## 4. Task A — Zero-shot 推理

直接使用基础模型，不提供任何示例。

**Prompt 格式**：描述评分标准 + 评论文本，要求模型输出单个数字（1-5）。

返回的 `zero_out` 是一个字典：
- `predictions_df`：含 `Review_id` 和 `Predicted_Rating` 的 DataFrame
- `debug_records`：每条样本的原始输出和解析详情
- `inference_seconds`：总推理耗时

In [12]:
import time
import pandas as pd
from model import build_zero_shot_prompt, generate_response, extract_rating_from_output

sample_row = test_df.iloc[6]
print(f'Review_id : {sample_row["Review_id"]}')
print(f'Title     : {sample_row.get("Title")}')
print(f'Review    : {str(sample_row["Review"])}')
true_answer = answer_df[answer_df['Review_id'] == sample_row['Review_id']]['rating_numeric'].values[0]
print(f'True_ans  : {true_answer}')

Review_id : 5123417064
Title     : Excellent except Terrible Staff
Review    : It was unplanned visit to this restaurant but we I and my friends was satisfied with the foods and drinks they served. But, one staff their who is thin and tall and if im not mistaken the name is Jayson he shows his rudeness to us when my lady friend calling his attention and we are pretty sure that with his awareness he just ignore and make a face to my friend. Then, when he passes in our table I notice he walked like a woman though his not by then I learned why he ignored my lady friend. We will try to comeback we hope we dont encounter him anymore.
True_ans  : 2

In [13]:
# 第 1 步：构建 prompt
sample_title = '' if pd.isna(sample_row.get('Title')) else str(sample_row.get('Title'))
sample_review = str(sample_row['Review'])
sample_prompt = build_zero_shot_prompt(title=sample_title, review=sample_review)
print(f'Prompt: \n'+sample_prompt)

Prompt:
Given the following restaurant review, please rate it from 1 to 5 stars, where:
- 1 star: Very poor experience
- 2 stars: Poor experience
- 3 stars: Average experience
- 4 stars: Good experience
- 5 stars: Excellent experience

Title: Excellent except Terrible Staff
Review: It was unplanned visit to this restaurant but we I and my friends was satisfied with the foods and drinks they served. But, one staff their who is thin and tall and if im not mistaken the name is Jayson he shows his rudeness to us when my lady friend calling his attention and we are pretty sure that with his awareness he just ignore and make a face to my friend. Then, when he passes in our table I notice he walked like a woman though his not by then I learned why he ignored my lady friend. We will try to comeback we hope we dont encounter him anymore.

Please provide only a single number (1, 2, 3, 4, or 5) as your rating.
Return format: `Rating: <digit>` (no explanation).
Rating:

In [14]:
# 第 2 步：调用模型生成
sample_raw_output = generate_response(
    model=base_model,
    tokenizer=tokenizer,
    prompt=sample_prompt,
    max_new_tokens=MAX_NEW_TOKENS,
)
print(f'模型原始输出: '+ repr(sample_raw_output))

The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

模型原始输出: 'Rating: 2'

In [15]:
# 第 3 步：解析评分
sample_predicted = extract_rating_from_output(sample_raw_output)
print(f'解析结果: {sample_predicted}')

解析结果: 2

In [16]:
ids = []
predictions = []
debug_records = []

start_time = time.time()

for step, (_, row) in enumerate(test_df.iterrows()):
    review_id = row['Review_id']
    title = '' if pd.isna(row.get('Title')) else str(row.get('Title'))
    review = str(row['Review'])

    # 第 1 步：构建 prompt
    prompt = build_zero_shot_prompt(title=title, review=review)

    # 第 2 步：调用模型生成
    raw_output = generate_response(
        model=base_model,
        tokenizer=tokenizer,
        prompt=prompt,
        max_new_tokens=MAX_NEW_TOKENS,
    )

    # 第 3 步：从模型输出中解析评分（1-5），解析失败默认为 3
    predicted_rating = extract_rating_from_output(raw_output)

    # 收集结果
    ids.append(review_id)
    predictions.append(predicted_rating)
    debug_records.append({
        'sample_idx': step,
        'review_id': review_id,
        'prompt': prompt,
        'raw_output': raw_output,
        'predicted_rating': predicted_rating,
    })

    # 每 10 条打印一次进度
    if (step + 1) % 10 == 0:
        elapsed = time.time() - start_time
        print(f'已处理 {step + 1}/{len(test_df)} 条，耗时 {elapsed:.1f}s')

total_time = time.time() - start_time

# 汇总结果
zero_predictions_df = pd.DataFrame({'Review_id': ids, 'Predicted_Rating': predictions})

zero_out = {
    'predictions_df': zero_predictions_df,
    'debug_records': debug_records,
    'inference_seconds': total_time,
    'sample_count': len(predictions),
}

print(f'\n推理完成：{zero_out["sample_count"]} 条')
print(f'总耗时  ：{zero_out["inference_seconds"]:.1f}s')
print(f'平均耗时：{zero_out["inference_seconds"] / zero_out["sample_count"]:.2f}s/样本')
zero_out['predictions_df'].head()

已处理 10/1007 条，耗时 1.2s
已处理 20/1007 条，耗时 2.4s
已处理 30/1007 条，耗时 3.5s
已处理 40/1007 条，耗时 4.7s
已处理 50/1007 条，耗时 5.8s
已处理 60/1007 条，耗时 7.0s
已处理 70/1007 条，耗时 8.1s
已处理 80/1007 条，耗时 9.3s
已处理 90/1007 条，耗时 10.5s
已处理 100/1007 条，耗时 11.7s
已处理 110/1007 条，耗时 12.9s
已处理 120/1007 条，耗时 14.1s
已处理 130/1007 条，耗时 15.2s
已处理 140/1007 条，耗时 16.4s
已处理 150/1007 条，耗时 17.6s
已处理 160/1007 条，耗时 18.9s
已处理 170/1007 条，耗时 20.0s
已处理 180/1007 条，耗时 21.2s
已处理 190/1007 条，耗时 22.3s
已处理 200/1007 条，耗时 23.4s
已处理 210/1007 条，耗时 24.6s
已处理 220/1007 条，耗时 25.7s
已处理 230/1007 条，耗时 26.8s
已处理 240/1007 条，耗时 28.0s
已处理 250/1007 条，耗时 29.1s
已处理 260/1007 条，耗时 30.3s
已处理 270/1007 条，耗时 31.4s
已处理 280/1007 条，耗时 32.6s
已处理 290/1007 条，耗时 33.8s
已处理 300/1007 条，耗时 35.0s
已处理 310/1007 条，耗时 36.2s
已处理 320/1007 条，耗时 37.3s
已处理 330/1007 条，耗时 38.5s
已处理 340/1007 条，耗时 39.6s
已处理 350/1007 条，耗时 40.8s
已处理 360/1007 条，耗时 42.0s
已处理 370/1007 条，耗时 43.1s
已处理 380/1007 条，耗时 44.3s
已处理 390/1007 条，耗时 45.5s
已处理 400/1007 条，耗时 46.6s
已处理 410/1007 条，耗时 47.8s
已处理 420/1007 条，耗时 48.9s
已处理 430/1007 条，耗时 50.1s
已处理 440/1007 条，耗时 51.2s
已处理 450/1007 条，耗时 52.3s
已处理 460/1007 条，耗时 53.5s
已处理 470/1007 条，耗时 54.6s
已处理 480/1007 条，耗时 55.7s
已处理 490/1007 条，耗时 56.9s
已处理 500/1007 条，耗时 58.0s
已处理 510/1007 条，耗时 59.2s
已处理 520/1007 条，耗时 60.4s
已处理 530/1007 条，耗时 61.5s
已处理 540/1007 条，耗时 62.7s
已处理 550/1007 条，耗时 63.8s
已处理 560/1007 条，耗时 65.0s
已处理 570/1007 条，耗时 66.1s
已处理 580/1007 条，耗时 67.2s
已处理 590/1007 条，耗时 68.4s
已处理 600/1007 条，耗时 69.5s
已处理 610/1007 条，耗时 70.6s
已处理 620/1007 条，耗时 71.8s
已处理 630/1007 条，耗时 72.9s
已处理 640/1007 条，耗时 74.1s
已处理 650/1007 条，耗时 75.2s
已处理 660/1007 条，耗时 76.3s
已处理 670/1007 条，耗时 77.5s
已处理 680/1007 条，耗时 78.6s
已处理 690/1007 条，耗时 79.8s
已处理 700/1007 条，耗时 80.9s
已处理 710/1007 条，耗时 82.0s
已处理 720/1007 条，耗时 83.2s
已处理 730/1007 条，耗时 84.3s
已处理 740/1007 条，耗时 85.5s
已处理 750/1007 条，耗时 86.6s
已处理 760/1007 条，耗时 87.7s
已处理 770/1007 条，耗时 88.9s
已处理 780/1007 条，耗时 90.0s
已处理 790/1007 条，耗时 91.1s
已处理 800/1007 条，耗时 92.3s
已处理 810/1007 条，耗时 93.4s
已处理 820/1007 条，耗时 94.5s
已处理 830/1007 条，耗时 95.7s
已处理 840/1007 条，耗时 96.8s
已处理 850/1007 条，耗时 98.0s
已处理 860/1007 条，耗时 99.1s
已处理 870/1007 条，耗时 100.2s
已处理 880/1007 条，耗时 101.3s
已处理 890/1007 条，耗时 102.5s
已处理 900/1007 条，耗时 103.6s
已处理 910/1007 条，耗时 104.7s
已处理 920/1007 条，耗时 105.9s
已处理 930/1007 条，耗时 107.0s
已处理 940/1007 条，耗时 108.2s
已处理 950/1007 条，耗时 109.3s
已处理 960/1007 条，耗时 110.5s
已处理 970/1007 条，耗时 111.6s
已处理 980/1007 条，耗时 112.7s
已处理 990/1007 条，耗时 113.9s
已处理 1000/1007 条，耗时 115.0s

推理完成：1007 条
总耗时  ：115.8s
平均耗时：0.11s/样本

    Review_id  Predicted_Rating
0  6204917469                 1
1  7226897287                 1
2  1264902203                 2
3  3692481359                 2
4  7677228495                 5

### 4.1 评估 Zero-shot 结果

In [17]:
from eval import evaluate_predictions

zero_metric = evaluate_predictions(zero_out["predictions_df"], answer_df)

print(f"Accuracy    : {zero_metric['accuracy']:.4f}")
print(f"Macro-F1    : {zero_metric['macro_f1']:.4f}")
print(f"Weighted-F1 : {zero_metric['weighted_f1']:.4f}")
print()
print(zero_metric["classification_report"])

Parse fallback rate: N/A (no parser tracking metadata)
Accuracy    : 0.4816
Macro-F1    : 0.4537
Weighted-F1 : 0.4485

              precision    recall  f1-score   support

      1 star       0.47      0.96      0.63       212
      2 star       0.30      0.24      0.27       223
      3 star       0.43      0.20      0.27       213
      4 star       0.47      0.34      0.39       169
      5 star       0.74      0.67      0.71       190

    accuracy                           0.48      1007
   macro avg       0.48      0.48      0.45      1007
weighted avg       0.47      0.48      0.45      1007

### 4.2 混淆矩阵

In [18]:
import pandas as pd

cm_zero = pd.DataFrame(
    zero_metric["confusion_matrix"],
    index=[f"True {i}★" for i in range(1, 6)],
    columns=[f"Pred {i}★" for i in range(1, 6)],
)
print("Zero-shot 混淆矩阵:")
cm_zero

Zero-shot 混淆矩阵:

         Pred 1★  Pred 2★  Pred 3★  Pred 4★  Pred 5★
True 1★      204        8        0        0        0
True 2★      168       54        1        0        0
True 3★       56       98       42       15        2
True 4★        4       19       46       57       43
True 5★        1        4        9       48      128

### 4.3 保存预测结果

In [19]:
zero_out["predictions_df"].to_csv(f"{OUTPUT_DIR}/zero_shot_predictions.csv", index=False)
print("已保存 zero_shot_predictions.csv")

已保存 zero_shot_predictions.csv

---
## 5. Task B.1.1 — N-shot In-Context Learning

在同一基础模型上，在 prompt 中插入 N 个带标注的示例（few-shot examples），引导模型仿照示例格式输出评分。

**示例库构建**：`build_example_library` 从训练集中每个评分等级各采样 `n_per_rating` 条，共最多 5×N 条。

推理时每条测试样本会从示例库中随机选 `n_shot` 条插入 prompt，使用确定性 hash seed 保证可复现。

In [15]:
import pandas as pd
import hashlib
from dataset import build_example_library
from model import build_nshot_prompt, generate_response, extract_rating_from_output

# 构建示例库
example_lib = build_example_library(train_split, n_per_rating=N_PER_RATING, seed=SEED)
print(f"示例库大小：{len(example_lib)} 条（每评分最多 {N_PER_RATING} 条）")

示例库大小：50 条（每评分最多 10 条）

In [16]:
# 取测试集第 1 行
sample_row = test_df.iloc[6]
review_id = sample_row["Review_id"]
print(f'Review_id : {review_id}')
print(f'Title     : {sample_row.get("Title")}')
print(f'Review    : {str(sample_row["Review"])}')
true_answer = answer_df[answer_df['Review_id'] == sample_row['Review_id']]['rating_numeric'].values[0]
print(f'True_ans  : {true_answer}')

Review_id : 5123417064
Title     : Excellent except Terrible Staff
Review    : It was unplanned visit to this restaurant but we I and my friends was satisfied with the foods and drinks they served. But, one staff their who is thin and tall and if im not mistaken the name is Jayson he shows his rudeness to us when my lady friend calling his attention and we are pretty sure that with his awareness he just ignore and make a face to my friend. Then, when he passes in our table I notice he walked like a woman though his not by then I learned why he ignored my lady friend. We will try to comeback we hope we dont encounter him anymore.
True_ans  : 2

In [17]:
# 第 1 步：哈希计算种子 & 构建 prompt
review_id_text = str(review_id)
stable_hash = int(hashlib.md5(review_id_text.encode("utf-8")).hexdigest()[:8], 16)
row_seed = SEED + (stable_hash % 1_000_000)

sample_title = '' if pd.isna(sample_row.get('Title')) else str(sample_row.get('Title'))
sample_review = str(sample_row['Review'])
sample_prompt = build_nshot_prompt(
    title=sample_title, 
    review=sample_review, 
    examples=example_lib,
    n=N_SHOT,
    seed=row_seed
)
print(f'动态种子: {row_seed}')
print(f'N-shot Prompt: \n' + sample_prompt)

动态种子: 584439
N-shot Prompt:
Given the following restaurant review, please rate it from 1 to 5 stars, where:
- 1 star: Very poor experience
- 2 stars: Poor experience
- 3 stars: Average experience
- 4 stars: Good experience
- 5 stars: Excellent experience

Here are some examples as below:
### Example 1
Title: Poor Choice of Restaurant
Review: We went last weekend on a Saturday, around 7pm. We came earlier so as to avoid the crowd. We just wanted to have a nice, quiet dinner with a lovely view. Unfortunately, one of our main dish did not turn out right. It is probably the worst Steak I've ever tried. It's tough and chewy that we had to send it back to the kitchen and ask the chef to rectify it. The chef just had to cook it again and gue...
Rating: 2

### Example 2
Title: Coming Home
Review: This is THE place for Sarawak laksa when I come back to my home town. Sarawakians have their favourite laksa haunts and this is mine because of my childhood memories of coming here on Sundays after mass at the nearby church.The place is always packed with locals and tourists because it's not just the food but the ambience of kopitiam; the Malaysian coffee shop with roti kahwin (kaya toast), kolo M...
Rating: 5

### Example 3
Title: Mediocre overpriced food
Review: I wouldn't say the food is terrible/inedible but for the price they are charging (and the portion they are serving), I'd expect much better food. This is the first time I've been here (did not visit previously as I heard they were always full/owners with terrible attitude) and it will be my last.Country Fried Chicken at RM21 - 2 small pieces of chicken, a small helping of mashed potatoes and green...
Rating: 2

### Example 4
Title: Cashier is sloooooooooowwwwwwww
Review: The food is superb (as usual), better than at MyTown's outlet but they do not serve a side salad as in MyTown's. We had tu queue TWICE, while waiting for the table (this is fine due to high traffic), HOWEVER, the lady at the cashier works at a snail pace, it took her a LONG time to confirm what has already been captured in the system and was distracted with her other colleagues doings. Service and...
Rating: 3

### Query Review
Title: Excellent except Terrible Staff
Review: It was unplanned visit to this restaurant but we I and my friends was satisfied with the foods and drinks they served. But, one staff their who is thin and tall and if im not mistaken the name is Jayson he shows his rudeness to us when my lady friend calling his attention and we are pretty sure that with his awareness he just ignore and make a face to my friend. Then, when he passes in our table I notice he walked like a woman though his not by then I learned why he ignored my lady friend. We will try to comeback we hope we dont encounter him anymore.

Please provide only a single number (1, 2, 3, 4, or 5) as your rating.
Return format: `Rating: <digit>` (no explanation).
Rating:

In [18]:
# 第 2 步：调用模型生成
sample_raw_output = generate_response(
    model=base_model,
    tokenizer=tokenizer,
    prompt=sample_prompt,
    max_new_tokens=MAX_NEW_TOKENS,
)
print(f'模型原始输出: '+repr(sample_raw_output))

模型原始输出: 'Rating: 5'

In [19]:
# 第 3 步：解析评分
sample_predicted = extract_rating_from_output(sample_raw_output)
print(f'解析结果: {sample_predicted}')

解析结果: 5

In [20]:
ids = []
predictions = []
debug_records = []

start_time = time.time()

for step, (_, row) in enumerate(test_df.iterrows()):
    review_id = row['Review_id']
    title = '' if pd.isna(row.get('Title')) else str(row.get('Title'))
    review = str(row['Review'])

    review_id_text = str(review_id)
    stable_hash = int(hashlib.md5(review_id_text.encode("utf-8")).hexdigest()[:8], 16)
    row_seed = SEED + (stable_hash % 1_000_000)

    # 第 1 步：构建 prompt
    prompt = build_nshot_prompt(
        title=title, 
        review=review, 
        examples=example_lib,
        n=N_SHOT,
        seed=row_seed
    )

    # 第 2 步：调用模型生成
    raw_output = generate_response(
        model=base_model,
        tokenizer=tokenizer,
        prompt=prompt,
        max_new_tokens=MAX_NEW_TOKENS,
    )

    # 第 3 步：从模型输出中解析评分（1-5），解析失败默认为 3
    predicted_rating = extract_rating_from_output(raw_output)

    # 收集结果
    ids.append(review_id)
    predictions.append(predicted_rating)
    debug_records.append({
        'sample_idx': step,
        'review_id': review_id,
        'prompt': prompt,
        'raw_output': raw_output,
        'predicted_rating': predicted_rating,
    })

    # 每 10 条打印一次进度
    if (step + 1) % 10 == 0:
        elapsed = time.time() - start_time
        print(f'已处理 {step + 1}/{len(test_df)} 条，耗时 {elapsed:.1f}s')

total_time = time.time() - start_time

# 汇总结果
nshot_predictions_df = pd.DataFrame({'Review_id': ids, 'Predicted_Rating': predictions})

nshot_out = {
    'predictions_df': nshot_predictions_df,
    'debug_records': debug_records,
    'inference_seconds': total_time,
    'sample_count': len(predictions),
}

print(f'\n推理完成：{nshot_out["sample_count"]} 条')
print(f'总耗时  ：{nshot_out["inference_seconds"]:.1f}s')
print(f'平均耗时：{nshot_out["inference_seconds"] / nshot_out["sample_count"]:.2f}s/样本')

已处理 10/1007 条，耗时 1.3s
已处理 20/1007 条，耗时 2.7s
已处理 30/1007 条，耗时 4.1s
已处理 40/1007 条，耗时 5.4s
已处理 50/1007 条，耗时 6.7s
已处理 60/1007 条，耗时 8.1s
已处理 70/1007 条，耗时 9.4s
已处理 80/1007 条，耗时 10.8s
已处理 90/1007 条，耗时 12.1s
已处理 100/1007 条，耗时 13.5s
已处理 110/1007 条，耗时 14.8s
已处理 120/1007 条，耗时 16.2s
已处理 130/1007 条，耗时 17.6s
已处理 140/1007 条，耗时 18.9s
已处理 150/1007 条，耗时 20.3s
已处理 160/1007 条，耗时 21.8s
已处理 170/1007 条，耗时 23.1s
已处理 180/1007 条，耗时 24.4s
已处理 190/1007 条，耗时 25.6s
已处理 200/1007 条，耗时 26.9s
已处理 210/1007 条，耗时 28.2s
已处理 220/1007 条，耗时 29.6s
已处理 230/1007 条，耗时 30.9s
已处理 240/1007 条，耗时 32.3s
已处理 250/1007 条，耗时 33.8s
已处理 260/1007 条，耗时 35.2s
已处理 270/1007 条，耗时 36.5s
已处理 280/1007 条，耗时 37.7s
已处理 290/1007 条，耗时 39.0s
已处理 300/1007 条，耗时 40.4s
已处理 310/1007 条，耗时 41.7s
已处理 320/1007 条，耗时 43.0s
已处理 330/1007 条，耗时 44.4s
已处理 340/1007 条，耗时 45.8s
已处理 350/1007 条，耗时 47.1s
已处理 360/1007 条，耗时 48.4s
已处理 370/1007 条，耗时 49.8s
已处理 380/1007 条，耗时 51.2s
已处理 390/1007 条，耗时 52.5s
已处理 400/1007 条，耗时 53.9s
已处理 410/1007 条，耗时 55.3s
已处理 420/1007 条，耗时 56.6s
已处理 430/1007 条，耗时 58.0s
已处理 440/1007 条，耗时 59.3s
已处理 450/1007 条，耗时 60.7s
已处理 460/1007 条，耗时 62.0s
已处理 470/1007 条，耗时 63.4s
已处理 480/1007 条，耗时 64.8s
已处理 490/1007 条，耗时 66.1s
已处理 500/1007 条，耗时 67.5s
已处理 510/1007 条，耗时 68.8s
已处理 520/1007 条，耗时 70.3s
已处理 530/1007 条，耗时 71.6s
已处理 540/1007 条，耗时 73.0s
已处理 550/1007 条，耗时 74.4s
已处理 560/1007 条，耗时 75.8s
已处理 570/1007 条，耗时 77.1s
已处理 580/1007 条，耗时 78.5s
已处理 590/1007 条，耗时 79.8s
已处理 600/1007 条，耗时 81.1s
已处理 610/1007 条，耗时 82.4s
已处理 620/1007 条，耗时 83.7s
已处理 630/1007 条，耗时 85.1s
已处理 640/1007 条，耗时 86.4s
已处理 650/1007 条，耗时 87.7s
已处理 660/1007 条，耗时 89.0s
已处理 670/1007 条，耗时 90.3s
已处理 680/1007 条，耗时 91.7s
已处理 690/1007 条，耗时 93.0s
已处理 700/1007 条，耗时 94.4s
已处理 710/1007 条，耗时 95.7s
已处理 720/1007 条，耗时 97.1s
已处理 730/1007 条，耗时 98.5s
已处理 740/1007 条，耗时 99.9s
已处理 750/1007 条，耗时 101.2s
已处理 760/1007 条，耗时 102.6s
已处理 770/1007 条，耗时 103.9s
已处理 780/1007 条，耗时 105.3s
已处理 790/1007 条，耗时 106.7s
已处理 800/1007 条，耗时 108.0s
已处理 810/1007 条，耗时 109.3s
已处理 820/1007 条，耗时 110.7s
已处理 830/1007 条，耗时 112.0s
已处理 840/1007 条，耗时 113.4s
已处理 850/1007 条，耗时 114.7s
已处理 860/1007 条，耗时 116.0s
已处理 870/1007 条，耗时 117.3s
已处理 880/1007 条，耗时 118.7s
已处理 890/1007 条，耗时 120.0s
已处理 900/1007 条，耗时 121.3s
已处理 910/1007 条，耗时 122.6s
已处理 920/1007 条，耗时 124.0s
已处理 930/1007 条，耗时 125.3s
已处理 940/1007 条，耗时 126.5s
已处理 950/1007 条，耗时 127.8s
已处理 960/1007 条，耗时 129.2s
已处理 970/1007 条，耗时 130.5s
已处理 980/1007 条，耗时 131.8s
已处理 990/1007 条，耗时 133.0s
已处理 1000/1007 条，耗时 134.3s

推理完成：1007 条
总耗时  ：135.2s
平均耗时：0.13s/样本

### 5.1 评估 N-shot 结果

In [21]:
nshot_metric = evaluate_predictions(nshot_out["predictions_df"], answer_df)

print(f"Accuracy    : {nshot_metric['accuracy']:.4f}")
print(f"Macro-F1    : {nshot_metric['macro_f1']:.4f}")
print(f"Weighted-F1 : {nshot_metric['weighted_f1']:.4f}")
print()
print(nshot_metric["classification_report"])

Accuracy    : 0.5065
Macro-F1    : 0.4390
Weighted-F1 : 0.4446

              precision    recall  f1-score   support

      1 star       0.52      0.77      0.62       212
      2 star       0.50      0.14      0.22       223
      3 star       0.52      0.63      0.57       213
      4 star       0.50      0.09      0.16       169
      5 star       0.49      0.87      0.62       190

    accuracy                           0.51      1007
   macro avg       0.51      0.50      0.44      1007
weighted avg       0.51      0.51      0.44      1007

### 5.2 混淆矩阵

In [22]:
cm_nshot = pd.DataFrame(
    nshot_metric["confusion_matrix"],
    index=[f"True {i}★" for i in range(1, 6)],
    columns=[f"Pred {i}★" for i in range(1, 6)],
)
print(f"{N_SHOT}-shot 混淆矩阵:")
cm_nshot

4-shot 混淆矩阵:

         Pred 1★  Pred 2★  Pred 3★  Pred 4★  Pred 5★
True 1★      163       10        8        2       29
True 2★      119       32       49        4       19
True 3★       27       21      134        4       27
True 4★        1        1       53       16       98
True 5★        5        0       14        6      165

### 5.3 保存预测结果

In [23]:
nshot_out["predictions_df"].to_csv(f"{OUTPUT_DIR}/nshot_predictions.csv", index=False)
print(f"已保存 nshot_predictions.csv")

已保存 nshot_predictions.csv

---
## 6. Task B.1.2 — LoRA 微调

对基础模型进行指令微调（SFT），使用 PEFT 的 LoRA 方法只训练少量参数。

**训练数据格式**（`prepare_instruction_data` 的输出）：
```
{ "instruction": "...", "input": "Title: ...\nReview: ...", "output": "4" }
```

**关键超参数**（可在 `LoraTrainingConfig` 中修改）：

| 参数 | 默认值 | 说明 |
|------|--------|------|
| `lora_rank` | 4 | LoRA 低秩矩阵的秩 |
| `lora_alpha` | 8 | LoRA 缩放系数 |
| `num_train_epochs` | 3 | 训练轮数 |
| `train_batch_size` | 8 | 每个设备 batch 大小 |
| `learning_rate` | 5e-5 | 学习率 |

In [24]:
from dataset import prepare_instruction_data
from train import LoraTrainingConfig, train_lora_model

# 构建指令样本
train_records = prepare_instruction_data(train_split)
val_records   = prepare_instruction_data(val_split)
print(f"训练指令样本: {len(train_records)} 条")
print(f"验证指令样本: {len(val_records)} 条")

# 示例：打印第一条样本
print("\n第一条训练样本:")
for k, v in train_records[0].items():
    print(f"{k}: {v[:80]}{'...' if len(v) > 80 else ''}")

训练指令样本: 7253 条
验证指令样本: 1814 条

第一条训练样本:
instruction: Given the following restaurant review, please rate it from 1 to 5 stars, where:
...
input: Title: A proper Indian
Review: It's not memorable or outstanding, but it is a go...
output: 4

### 6.1 配置 & 启动训练

> ⚠️ **注意**：训练会覆盖 `base_model` 的 adapter 状态。若需重跑 Task A/B.1.1，请重新执行 Section 3 重新加载基础模型。

In [25]:
cfg = LoraTrainingConfig(
    output_dir=LORA_CHECKPOINT_DIR,
    final_dir=LORA_FINAL_DIR,
    # 调试时可减少训练样本和 epoch
    # max_train_samples=100,
    # num_train_epochs=1,
)

train_res = train_lora_model(
    base_model=base_model,
    tokenizer=tokenizer,
    train_records=train_records,
    val_records=val_records,
    config=cfg,
)

print(f"训练完成 ✓")
print(f"总耗时      : {train_res['train_seconds']:.1f}s")
print(f"训练样本数  : {train_res['train_samples']}")
print(f"验证样本数  : {train_res['val_samples']}")
print(f"模型保存路径: {train_res['output_dir']}")

训练完成 ✓
总耗时      : 16765.5s
训练样本数  : 7253
验证样本数  : 1814
模型保存路径: ../qwen_lora_final

---
## 7. Task B.1.2 — LoRA 推理

将 LoRA adapter 合并（merge）到基础模型权重中，再进行推理。

**Merge 的好处**：推理速度与原始模型相同，无 adapter 额外开销。

> 若已有训练好的 adapter，可以直接修改 `lora_dir` 跳过 Section 6 直接执行本节。

In [26]:
from model import load_merged_lora_model

lora_dir = train_res["output_dir"]

tok_lora, merged_model, lora_device = load_merged_lora_model(
    base_model_name=MODEL_NAME,
    lora_dir=lora_dir,
    use_modelscope=USE_MODELSCOPE,
    cache_dir=MODEL_CACHE_DIR,
)

print(f"LoRA merge 完成 ✓  设备: {lora_device.device_type}")

本地缓存命中，跳过下载: ..\models\Qwen\Qwen2.5-0.5B-Instruct

Loading weights: 100%|██████████| 290/290 [00:00<00:00, 1871.96it/s]

LoRA merge 完成 ✓  设备: cuda

## LoRA微调后推理

In [27]:
import pandas as pd
from model import build_finetuned_prompt, generate_response, extract_rating_from_output

# 取测试集
sample_row = test_df.iloc[6]
review_id = sample_row["Review_id"]
print(f'Review_id : {review_id}')
print(f'Title     : {sample_row.get("Title")}')
print(f'Review    : {str(sample_row["Review"])[:200]}...')
true_answer = answer_df[answer_df['Review_id'] == sample_row['Review_id']]['rating_numeric'].values[0]
print(f'True_ans  : {true_answer}')

Review_id : 5123417064
Title     : Excellent except Terrible Staff
Review    : It was unplanned visit to this restaurant but we I and my friends was satisfied with the foods and drinks they served. But, one staff their who is thin and tall and if im not mistaken the name is Jays...
True_ans  : 2

In [28]:
# 第 1 步：构建微调模型专用的 Prompt
sample_title = '' if pd.isna(sample_row.get('Title')) else str(sample_row.get('Title'))
sample_review = str(sample_row['Review'])
sample_prompt = build_finetuned_prompt(title=sample_title, review=sample_review)
print(f'Zero-shot Prompt:\n' + sample_prompt)

Zero-shot Prompt:
Given the following restaurant review, please rate it from 1 to 5 stars, where:
- 1 star: Very poor experience
- 2 stars: Poor experience
- 3 stars: Average experience
- 4 stars: Good experience
- 5 stars: Excellent experience

Title: Excellent except Terrible Staff
Review: It was unplanned visit to this restaurant but we I and my friends was satisfied with the foods and drinks they served. But, one staff their who is thin and tall and if im not mistaken the name is Jayson he shows his rudeness to us when my lady friend calling his attention and we are pretty sure that with his awareness he just ignore and make a face to my friend. Then, when he passes in our table I notice he walked like a woman though his not by then I learned why he ignored my lady friend. We will try to comeback we hope we dont encounter him anymore.

Please provide only a single number (1, 2, 3, 4, or 5) as your rating.
Return format: `Rating: <digit>` (no explanation).
Rating:

In [ ]:
# 调用微调后的模型生成（挂载 LoRA 权重）
sample_raw_output = generate_response(
    model=merged_model,
    tokenizer=tok_lora,
    prompt=sample_prompt,
    max_new_tokens=MAX_NEW_TOKENS,
)
print(f'模型原始输出: ' + repr(sample_raw_output))

模型原始输出: '2'

In [30]:
# 第 3 步：解析评级数字
sample_predicted = extract_rating_from_output(sample_raw_output)
print(f'Rating:  {sample_predicted}')

Rating:  2

In [31]:
import time
import pandas as pd
from model import build_finetuned_prompt, generate_response, extract_rating_from_output

ids = []
predictions = []
debug_records = []

start_time = time.time()

for step, (_, row) in enumerate(test_df.iterrows()):
    review_id = row['Review_id']
    title = '' if pd.isna(row.get('Title')) else str(row.get('Title'))
    review = str(row['Review'])

    # 第 1 步：构建 Prompt (Zero-shot)
    prompt = build_finetuned_prompt(title=title, review=review)

    # 第 2 步：调用模型生成
    raw_output = generate_response(
        model=merged_model,
        tokenizer=tok_lora,       
        prompt=prompt,
        max_new_tokens=MAX_NEW_TOKENS,
    )

    # 第 3 步：解析评分
    predicted_rating = extract_rating_from_output(raw_output)

    # 收集结果
    ids.append(review_id)
    predictions.append(predicted_rating)
    debug_records.append({
        'sample_idx': step,
        'review_id': review_id,
        'prompt': prompt,
        'raw_output': raw_output,
        'predicted_rating': predicted_rating,
    })

    # 每 10 条打印一次进度
    if (step + 1) % 10 == 0:
        elapsed = time.time() - start_time
        print(f'已处理 {step + 1}/{len(test_df)} 条，耗时 {elapsed:.1f}s')

total_time = time.time() - start_time

# 汇总结果打包
lora_predictions_df = pd.DataFrame({'Review_id': ids, 'Predicted_Rating': predictions})
lora_out = {
    'predictions_df': lora_predictions_df,
    'debug_records': debug_records,
    'inference_seconds': total_time,
    'sample_count': len(predictions),
}

print(f'\n推理完成：{lora_out["sample_count"]} 条')
print(f'总耗时  ：{lora_out["inference_seconds"]:.1f}s')
print(f'平均耗时：{lora_out["inference_seconds"] / lora_out["sample_count"]:.2f}s/样本')

已处理 10/1007 条，耗时 1.1s
已处理 20/1007 条，耗时 2.0s
已处理 30/1007 条，耗时 7.8s
已处理 40/1007 条，耗时 8.8s
已处理 50/1007 条，耗时 9.9s
已处理 60/1007 条，耗时 10.8s
已处理 70/1007 条，耗时 11.7s
已处理 80/1007 条，耗时 18.2s
已处理 90/1007 条，耗时 19.2s
已处理 100/1007 条，耗时 20.1s
已处理 110/1007 条，耗时 21.0s
已处理 120/1007 条，耗时 22.2s
已处理 130/1007 条，耗时 23.1s
已处理 140/1007 条，耗时 24.1s
已处理 150/1007 条，耗时 25.3s
已处理 160/1007 条，耗时 46.7s
已处理 170/1007 条，耗时 47.5s
已处理 180/1007 条，耗时 48.4s
已处理 190/1007 条，耗时 49.3s
已处理 200/1007 条，耗时 50.3s
已处理 210/1007 条，耗时 51.2s
已处理 220/1007 条，耗时 52.3s
已处理 230/1007 条，耗时 53.3s
已处理 240/1007 条，耗时 54.2s
已处理 250/1007 条，耗时 55.2s
已处理 260/1007 条，耗时 56.2s
已处理 270/1007 条，耗时 57.1s
已处理 280/1007 条，耗时 58.0s
已处理 290/1007 条，耗时 58.9s
已处理 300/1007 条，耗时 59.9s
已处理 310/1007 条，耗时 61.0s
已处理 320/1007 条，耗时 62.0s
已处理 330/1007 条，耗时 62.9s
已处理 340/1007 条，耗时 63.9s
已处理 350/1007 条，耗时 64.8s
已处理 360/1007 条，耗时 72.3s
已处理 370/1007 条，耗时 73.5s
已处理 380/1007 条，耗时 74.5s
已处理 390/1007 条，耗时 75.4s
已处理 400/1007 条，耗时 76.4s
已处理 410/1007 条，耗时 77.4s
已处理 420/1007 条，耗时 78.3s
已处理 430/1007 条，耗时 79.4s
已处理 440/1007 条，耗时 80.3s
已处理 450/1007 条，耗时 81.2s
已处理 460/1007 条，耗时 82.2s
已处理 470/1007 条，耗时 83.1s
已处理 480/1007 条，耗时 84.0s
已处理 490/1007 条，耗时 85.0s
已处理 500/1007 条，耗时 86.0s
已处理 510/1007 条，耗时 87.0s
已处理 520/1007 条，耗时 105.9s
已处理 530/1007 条，耗时 106.8s
已处理 540/1007 条，耗时 107.8s
已处理 550/1007 条，耗时 114.1s
已处理 560/1007 条，耗时 115.0s
已处理 570/1007 条，耗时 116.1s
已处理 580/1007 条，耗时 117.2s
已处理 590/1007 条，耗时 118.1s
已处理 600/1007 条，耗时 119.0s
已处理 610/1007 条，耗时 120.0s
已处理 620/1007 条，耗时 120.9s
已处理 630/1007 条，耗时 122.0s
已处理 640/1007 条，耗时 123.0s
已处理 650/1007 条，耗时 124.0s
已处理 660/1007 条，耗时 124.9s
已处理 670/1007 条，耗时 125.8s
已处理 680/1007 条，耗时 126.8s
已处理 690/1007 条，耗时 127.7s
已处理 700/1007 条，耗时 128.7s
已处理 710/1007 条，耗时 129.8s
已处理 720/1007 条，耗时 131.0s
已处理 730/1007 条，耗时 132.0s
已处理 740/1007 条，耗时 132.9s
已处理 750/1007 条，耗时 133.8s
已处理 760/1007 条，耗时 140.3s
已处理 770/1007 条，耗时 141.2s
已处理 780/1007 条，耗时 142.1s
已处理 790/1007 条，耗时 143.1s
已处理 800/1007 条，耗时 144.0s
已处理 810/1007 条，耗时 145.0s
已处理 820/1007 条，耗时 145.9s
已处理 830/1007 条，耗时 146.8s
已处理 840/1007 条，耗时 147.9s
已处理 850/1007 条，耗时 148.9s
已处理 860/1007 条，耗时 149.8s
已处理 870/1007 条，耗时 150.7s
已处理 880/1007 条，耗时 151.5s
已处理 890/1007 条，耗时 152.5s
已处理 900/1007 条，耗时 153.4s
已处理 910/1007 条，耗时 154.5s
已处理 920/1007 条，耗时 155.6s
已处理 930/1007 条，耗时 156.7s
已处理 940/1007 条，耗时 157.6s
已处理 950/1007 条，耗时 158.6s
已处理 960/1007 条，耗时 168.5s
已处理 970/1007 条，耗时 169.4s
已处理 980/1007 条，耗时 170.3s
已处理 990/1007 条，耗时 171.2s
已处理 1000/1007 条，耗时 172.2s

推理完成：1007 条
总耗时  ：172.8s
平均耗时：0.17s/样本

### 7.1 评估 LoRA 结果

In [32]:
lora_metric = evaluate_predictions(lora_out["predictions_df"], answer_df)

print(f"Accuracy    : {lora_metric['accuracy']:.4f}")
print(f"Macro-F1    : {lora_metric['macro_f1']:.4f}")
print(f"Weighted-F1 : {lora_metric['weighted_f1']:.4f}")
print()
print(lora_metric["classification_report"])

Accuracy    : 0.6216
Macro-F1    : 0.6214
Weighted-F1 : 0.6223

              precision    recall  f1-score   support

      1 star       0.73      0.66      0.69       212
      2 star       0.53      0.59      0.56       223
      3 star       0.63      0.56      0.60       213
      4 star       0.52      0.53      0.52       169
      5 star       0.71      0.76      0.73       190

    accuracy                           0.62      1007
   macro avg       0.62      0.62      0.62      1007
weighted avg       0.63      0.62      0.62      1007

### 7.2 混淆矩阵

In [33]:
cm_lora = pd.DataFrame(
    lora_metric["confusion_matrix"],
    index=[f"True {i}★" for i in range(1, 6)],
    columns=[f"Pred {i}★" for i in range(1, 6)],
)
print("LoRA 混淆矩阵:")
cm_lora

LoRA 混淆矩阵:

         Pred 1★  Pred 2★  Pred 3★  Pred 4★  Pred 5★
True 1★      140       69        3        0        0
True 2★       49      132       42        0        0
True 3★        2       46      120       43        2
True 4★        1        1       21       90       56
True 5★        1        0        4       41      144

### 7.3 保存预测结果

In [34]:
lora_out["predictions_df"].to_csv(f"{OUTPUT_DIR}/lora_predictions.csv", index=False)
print("已保存 lora_predictions.csv")

已保存 lora_predictions.csv

---
## 8. 结果汇总对比

将三条路线的指标汇总到一张表，方便撰写报告。

In [35]:
comparison = pd.DataFrame([
    {
        "Method"     : "Task A: Zero-shot",
        "Accuracy"   : round(zero_metric["accuracy"],   4),
        "Macro-F1"   : round(zero_metric["macro_f1"],   4),
        "Weighted-F1": round(zero_metric["weighted_f1"],4),
        "Time(s)"    : round(zero_out["inference_seconds"], 1),
        "s/sample"   : round(zero_out["inference_seconds"] / zero_out["sample_count"], 3),
    },
    {
        "Method"     : f"Task B.1.1: {N_SHOT}-shot ICL",
        "Accuracy"   : round(nshot_metric["accuracy"],   4),
        "Macro-F1"   : round(nshot_metric["macro_f1"],   4),
        "Weighted-F1": round(nshot_metric["weighted_f1"],4),
        "Time(s)"    : round(nshot_out["inference_seconds"], 1),
        "s/sample"   : round(nshot_out["inference_seconds"] / nshot_out["sample_count"], 3),
    },
    {
        "Method"     : "Task B.1.2: LoRA Fine-tuned",
        "Accuracy"   : round(lora_metric["accuracy"],   4),
        "Macro-F1"   : round(lora_metric["macro_f1"],   4),
        "Weighted-F1": round(lora_metric["weighted_f1"],4),
        "Time(s)"    : round(lora_out["inference_seconds"], 1),
        "s/sample"   : round(lora_out["inference_seconds"] / lora_out["sample_count"], 3),
    },
])

comparison

,Method,Accuracy,Macro-F1,Weighted-F1,Time(s),s/sample
0,Task A: Zero-shot,0.4816,0.4537,0.4485,118.0,0.117
1,Task B.1.1: 4-shot ICL,0.5065,0.4390,0.4446,135.2,0.134
2,Task B.1.2: LoRA Fine-tuned,0.6216,0.6214,0.6223,172.8,0.172

In [36]:
comparison.to_csv(f"{OUTPUT_DIR}/comparison_results.csv", index=False)
print("已保存 comparison_results.csv")

已保存 comparison_results.csv

---
## 9. Debug：查看原始模型输出

对比不同方法对同一条评论的原始输出，便于分析模型行为。

In [37]:
# 查看详细预测 debug 信息
print("=== Zero-shot debug ===")
for rec in zero_out["debug_records"]:
    print(f"[{rec['review_id']}] pred={rec['predicted_rating']}  raw='{rec['raw_output']}'")

print()
print("=== N-shot debug ===")
for rec in nshot_out["debug_records"]:
    print(f"[{rec['review_id']}] pred={rec['predicted_rating']}  raw='{rec['raw_output']}'")

print()
print("=== LoRA debug ===")
for rec in lora_out["debug_records"]:
    print(f"[{rec['review_id']}] pred={rec['predicted_rating']}  raw='{rec['raw_output']}'")

=== Zero-shot debug ===
[6204917469] pred=1  raw='Rating: 1'
[7226897287] pred=1  raw='Rating: 1'
[1264902203] pred=2  raw='Rating: 2'
[3692481359] pred=2  raw='Rating: 2'
[7677228495] pred=5  raw='Rating: 5'
[1019631414] pred=1  raw='Rating: 1'
[5123417064] pred=2  raw='Rating: 2'
[5676789481] pred=2  raw='Rating: 2'
[9868191978] pred=5  raw='Rating: 5'
[6847353347] pred=1  raw='Rating: 1'
[6568314410] pred=1  raw='Rating: 1'
[5310406185] pred=3  raw='Rating: 3'
[1801252082] pred=1  raw='Rating: 1'
[9739603911] pred=1  raw='Rating: 1'
[3074861604] pred=1  raw='Rating: 1'
[7979374648] pred=4  raw='Rating: 4'
[7951938872] pred=4  raw='Rating: 4'
[6793182662] pred=5  raw='Rating: 5'
[4016545934] pred=5  raw='Rating: 5'
[5543952715] pred=1  raw='Rating: 1'
[1847313872] pred=1  raw='Rating: 1'
[2860929080] pred=2  raw='Rating: 2'
[6249981723] pred=2  raw='Rating: 2'
[8414869219] pred=1  raw='Rating: 1'
[3434596438] pred=1  raw='Rating: 1'
[8842256948] pred=1  raw='Rating: 1'
[4371181493] pred=1  raw='Rating: 1'
[5209722404] pred=1  raw='Rating: 1'
[5717400354] pred=1  raw='Rating: 1'
[2583892308] pred=1  raw='Rating: 1'
[2569386211] pred=1  raw='Rating: 1'
[8570447500] pred=4  raw='Rating: 4'
[5102300785] pred=1  raw='Rating: 1'
[5598260348] pred=1  raw='Rating: 1'
[4765968770] pred=1  raw='Rating: 1'
[5367019475] pred=4  raw='Rating: 4'
[9350751302] pred=1  raw='Rating: 1'
[2344609998] pred=2  raw='Rating: 2'
[9739381366] pred=1  raw='Rating: 1'
[2601220850] pred=2  raw='Rating: 2'
[8304785108] pred=5  raw='Rating: 5'
[4601782330] pred=1  raw='Rating: 1'
[2898487266] pred=5  raw='Rating: 5'
[7946987455] pred=2  raw='Rating: 2'
[1713487126] pred=1  raw='Rating: 1'
[2524719644] pred=1  raw='Rating: 1'
[9718124459] pred=4  raw='Rating: 4'
[4274949495] pred=1  raw='Rating: 1'
[9492572181] pred=3  raw='Rating: 3'
[9447612266] pred=1  raw='Rating: 1'
[6220283683] pred=5  raw='Rating: 5'
[3172828003] pred=5  raw='Rating: 5'
[7344987864] pred=2  raw='Rating: 2'
[2808924566] pred=1  raw='Rating: 1'
[2044064423] pred=1  raw='Rating: 1'
[9508306537] pred=5  raw='Rating: 5'
[3379467907] pred=1  raw='Rating: 1'
[8366187092] pred=5  raw='Rating: 5'
[8911632348] pred=1  raw='Rating: 1'
[8786188171] pred=1  raw='Rating: 1'
[1028745821] pred=3  raw='Rating: 3'
[3657325888] pred=1  raw='Rating: 1'
[8095159374] pred=1  raw='Rating: 1'
[7312557669] pred=2  raw='Rating: 2'
[4242138399] pred=1  raw='Rating: 1'
[6662238285] pred=1  raw='Rating: 1'
[5819081504] pred=1  raw='Rating: 1'
[9865171529] pred=3  raw='Rating: 3'
[8314212548] pred=2  raw='Rating: 2'
[3607461993] pred=1  raw='Rating: 1'
[1227768665] pred=5  raw='Rating: 5'
[4330727909] pred=5  raw='Rating: 5'
[5791556819] pred=3  raw='Rating: 3'
[1090954500] pred=1  raw='Rating: 1'
[2106357508] pred=5  raw='Rating: 5'
[7432823677] pred=4  raw='Rating: 4'
[9049423295] pred=2  raw='Rating: 2'
[3039660439] pred=2  raw='Rating: 2'
[1605832440] pred=3  raw='Rating: 3'
[1104694148] pred=1  raw='Rating: 1'
[9860795924] pred=5  raw='Rating: 5'
[3336526677] pred=4  raw='Rating: 4'
[7131307734] pred=3  raw='Rating: 3'
[5020389758] pred=4  raw='Rating: 4'
[8045819621] pred=5  raw='Rating: 5'
[1354519823] pred=3  raw='Rating: 3'
[3181031556] pred=1  raw='Rating: 1'
[2246694822] pred=1  raw='Rating: 1'
[1270221719] pred=2  raw='Rating: 2'
[4137299949] pred=1  raw='Rating: 1'
[8095347238] pred=1  raw='Rating: 1'
[2051459142] pred=1  raw='Rating: 1'
[7953029198] pred=1  raw='Rating: 1'
[5931187590] pred=3  raw='Rating: 3'
[2329030720] pred=2  raw='Rating: 2'
[1357418114] pred=1  raw='Rating: 1'
[4524768382] pred=3  raw='Rating: 3'
[4217958111] pred=1  raw='Rating: 1'
[8941551119] pred=5  raw='Rating: 5'
[7500298969] pred=1  raw='Rating: 1'
[4390252050] pred=1  raw='Rating: 1'
[8810351368] pred=2  raw='Rating: 2'
[4625804190] pred=4  raw='Rating: 4'
[8130537444] pred=1  raw='Rating: 1'
[4032639554] pred=2  raw='Rating: 2'
[2454980573] pred=1  raw='Rating: 1'
[7559344712] pred=1  raw='Rating: 1'
[1939458405] pred=4  raw='Rating: 4'
[4811663035] pred=4  raw='Rating: 4'
[3716426586] pred=1  raw='Rating: 1'
[6167618705] pred=5  raw='Rating: 5'
[7715737704] pred=1  raw='Rating: 1'
[1459074498] pred=1  raw='Rating: 1'
[5038393721] pred=5  raw='Rating: 5'
[1306534890] pred=1  raw='Rating: 1'
[8204779636] pred=4  raw='Rating: 4'
[3686778049] pred=1  raw='Rating: 1'
[9684912143] pred=5  raw='Rating: 5'
[9792265648] pred=1  raw='Rating: 1'
[6143450249] pred=2  raw='Rating: 2'
[5426642176] pred=3  raw='Rating: 3'
[3820203083] pred=1  raw='Rating: 1'
[7385499461] pred=1  raw='Rating: 1'
[2088225569] pred=2  raw='Rating: 2'
[8551402795] pred=1  raw='Rating: 1'
[5061832020] pred=3  raw='Rating: 3'
[5887283156] pred=5  raw='Rating: 5'
[1477800043] pred=3  raw='Rating: 3'
[4940323111] pred=3  raw='Rating: 3'
[9858579643] pred=5  raw='Rating: 5'
[8675816508] pred=1  raw='Rating: 1'
[5482340297] pred=4  raw='Rating: 4'
[8214603539] pred=2  raw='Rating: 2'
[4729753889] pred=1  raw='Rating: 1'
[6255881819] pred=2  raw='Rating: 2'
[3847614271] pred=1  raw='Rating: 1'
[4689930867] pred=2  raw='Rating: 2'
[9812157708] pred=1  raw='Rating: 1'
[6789140063] pred=2  raw='Rating: 2'
[3641733058] pred=1  raw='Rating: 1'
[8420579598] pred=2  raw='Rating: 2'
[4276303947] pred=3  raw='Rating: 3'
[2400343320] pred=1  raw='Rating: 1'
[5917363086] pred=5  raw='Rating: 5'
[3572558604] pred=5  raw='Rating: 5'
[6777367908] pred=2  raw='Rating: 2'
[3432676312] pred=3  raw='Rating: 3'
[6641131422] pred=2  raw='Rating: 2'
[3809674617] pred=3  raw='Rating: 3'
[3258420441] pred=2  raw='Rating: 2'
[4578101287] pred=1  raw='Rating: 1'
[6514921921] pred=1  raw='Rating: 1'
[6661332854] pred=1  raw='Rating: 1'
[9885921537] pred=1  raw='Rating: 1'
[2232503481] pred=4  raw='Rating: 4'
[2315783119] pred=4  raw='Rating: 4'
[7370561982] pred=2  raw='Rating: 2'
[8606259839] pred=1  raw='Rating: 1'
[7124326341] pred=1  raw='Rating: 1'
[3559305268] pred=4  raw='Rating: 4'
[6267151642] pred=4  raw='Rating: 4'
[9082107354] pred=1  raw='Rating: 1'
[2021122739] pred=3  raw='Rating: 3'
[2556011185] pred=1  raw='Rating: 1'
[6505118027] pred=3  raw='Rating: 3'
[2547213246] pred=1  raw='Rating: 1'
[8873729712] pred=2  raw='Rating: 2'
[4321505631] pred=1  raw='Rating: 1'
[4610152162] pred=5  raw='Rating: 5'
[6480708314] pred=1  raw='Rating: 1'
[1006452886] pred=1  raw='Rating: 1'
[3544376782] pred=2  raw='Rating: 2'
[5285396383] pred=1  raw='Rating: 1'
[3379638605] pred=1  raw='Rating: 1'
[7346022675] pred=2  raw='Rating: 2'
[5702161795] pred=1  raw='Rating: 1'
[4836358644] pred=5  raw='Rating: 5'
[8324944165] pred=1  raw='Rating: 1'
[3414230563] pred=5  raw='Rating: 5'
[5866229686] pred=1  raw='Rating: 1'
[5660017217] pred=3  raw='Rating: 3'
[6167604548] pred=5  raw='Rating: 5'
[7600836806] pred=5  raw='Rating: 5'
[5538308693] pred=5  raw='Rating: 5'
[5982616587] pred=1  raw='Rating: 1'
[1686159702] pred=2  raw='Rating: 2'
[7789164434] pred=5  raw='Rating: 5'
[9449792595] pred=1  raw='Rating: 1'
[2899604930] pred=2  raw='Rating: 2'
[1678415012] pred=5  raw='Rating: 5'
[3359766614] pred=5  raw='Rating: 5'
[2119364746] pred=5  raw='Rating: 5'
[6350576997] pred=4  raw='Rating: 4'
[1831578978] pred=4  raw='Rating: 4'
[1883099811] pred=1  raw='Rating: 1'
[8885556991] pred=1  raw='Rating: 1'
[6485800920] pred=2  raw='Rating: 2'
[6237610936] pred=2  raw='Rating: 2'
[2517594792] pred=4  raw='Rating: 4'
[9182514440] pred=1  raw='Rating: 1'
[4197922343] pred=5  raw='Rating: 5'
[7852141407] pred=2  raw='Rating: 2'
[4250755090] pred=2  raw='Rating: 2'
[5299683138] pred=1  raw='Rating: 1'
[8673827198] pred=1  raw='Rating: 1'
[4510821025] pred=1  raw='Rating: 1'
[9717721819] pred=2  raw='Rating: 2'
[4774528429] pred=1  raw='Rating: 1'
[6481163590] pred=3  raw='Rating: 3'
[6041009239] pred=1  raw='Rating: 1'
[2489705173] pred=1  raw='Rating: 1'
[2832264663] pred=2  raw='Rating: 2'
[1296396079] pred=1  raw='Rating: 1'
[7696641407] pred=1  raw='Rating: 1'
[7250790608] pred=1  raw='Rating: 1'
[3730783838] pred=1  raw='Rating: 1'
[4632372138] pred=4  raw='Rating: 4'
[3566988484] pred=1  raw='Rating: 1'
[2656068890] pred=4  raw='Rating: 4'
[6337695155] pred=4  raw='Rating: 4'
[4347935136] pred=2  raw='Rating: 2'
[7295804264] pred=3  raw='Rating: 3'
[5240441282] pred=1  raw='Rating: 1'
[4866967718] pred=1  raw='Rating: 1'
[3471714031] pred=5  raw='Rating: 5'
[5214404730] pred=1  raw='Rating: 1'
[9950247920] pred=5  raw='Rating: 5'
[5245635668] pred=2  raw='Rating: 2'
[6990138392] pred=2  raw='Rating: 2'
[6495588556] pred=4  raw='Rating: 4'
[8626372079] pred=1  raw='Rating: 1'
[3787599983] pred=1  raw='Rating: 1'
[7471889329] pred=1  raw='Rating: 1'
[2017822687] pred=1  raw='Rating: 1'
[9024561627] pred=1  raw='Rating: 1'
[9935731629] pred=1  raw='Rating: 1'
[3220522665] pred=4  raw='Rating: 4'
[9443077349] pred=1  raw='Rating: 1'
[2885648463] pred=2  raw='Rating: 2'
[4137133107] pred=2  raw='Rating: 2'
[8565894350] pred=2  raw='Rating: 2'
[7407640667] pred=1  raw='Rating: 1'
[8892684489] pred=2  raw='Rating: 2'
[4126027438] pred=2  raw='Rating: 2'
[1702487014] pred=2  raw='Rating: 2'
[4669543137] pred=5  raw='Rating: 5'
[8620219729] pred=1  raw='Rating: 1'
[1536469229] pred=2  raw='Rating: 2'
[2192969623] pred=5  raw='Rating: 5'
[7960179224] pred=5  raw='Rating: 5'
[1720305279] pred=1  raw='Rating: 1'
[7766607421] pred=1  raw='Rating: 1'
[5893495874] pred=1  raw='Rating: 1'
[1924884114] pred=1  raw='Rating: 1'
[8848101938] pred=1  raw='Rating: 1'
[9413575402] pred=1  raw='Rating: 1'
[7643343426] pred=5  raw='Rating: 5'
[5306304255] pred=3  raw='Rating: 3'
[1772193795] pred=2  raw='Rating: 2'
[2207781299] pred=5  raw='Rating: 5'
[2881390550] pred=2  raw='Rating: 2'
[9396139618] pred=5  raw='Rating: 5'
[2350841415] pred=3  raw='Rating: 3'
[1964972337] pred=4  raw='Rating: 4'
[3739235874] pred=1  raw='Rating: 1'
[4705580018] pred=2  raw='Rating: 2'
[2657883679] pred=5  raw='Rating: 5'
[8439551507] pred=1  raw='Rating: 1'
[7316596816] pred=2  raw='Rating: 2'
[4370708606] pred=2  raw='Rating: 2'
[3437559678] pred=1  raw='Rating: 1'
[8322131133] pred=1  raw='Rating: 1'
[4587312164] pred=2  raw='Rating: 2'
[3984816692] pred=2  raw='Rating: 2'
[5279508469] pred=1  raw='Rating: 1'
[2819761615] pred=5  raw='Rating: 5'
[1949619239] pred=5  raw='Rating: 5'
[1902311112] pred=5  raw='Rating: 5'
[8148518833] pred=5  raw='Rating: 5'
[3123586074] pred=3  raw='Rating: 3'
[2564369319] pred=2  raw='Rating: 2'
[8396028979] pred=5  raw='Rating: 5'
[7325458566] pred=1  raw='Rating: 1'
[1778682331] pred=3  raw='Rating: 3'
[4785470664] pred=5  raw='Rating: 5'
[6203459886] pred=1  raw='Rating: 1'
[4364821320] pred=1  raw='Rating: 1'
[3682492053] pred=1  raw='Rating: 1'
[5249517200] pred=1  raw='Rating: 1'
[1068695684] pred=1  raw='Rating: 1'
[5632748404] pred=1  raw='Rating: 1'
[2457111390] pred=2  raw='Rating: 2'
[6858516872] pred=1  raw='Rating: 1'
[8162448672] pred=3  raw='Rating: 3'
[7693456058] pred=2  raw='Rating: 2'
[5823470653] pred=2  raw='Rating: 2'
[3374533670] pred=1  raw='Rating: 1'
[9470564540] pred=1  raw='Rating: 1'
[6338544047] pred=2  raw='Rating: 2'
[6726543873] pred=5  raw='Rating: 5'
[4074650933] pred=4  raw='Rating: 4'
[9285422975] pred=1  raw='Rating: 1'
[6504242009] pred=5  raw='Rating: 5'
[1322203931] pred=1  raw='Rating: 1'
[2747393718] pred=4  raw='Rating: 4'
[5304719581] pred=2  raw='Rating: 2'
[7701693620] pred=5  raw='Rating: 5'
[6646811353] pred=1  raw='Rating: 1'
[1701547652] pred=3  raw='Rating: 3'
[9168178689] pred=2  raw='Rating: 2'
[2712625788] pred=1  raw='Rating: 1'
[5211393359] pred=3  raw='Rating: 3'
[6087501834] pred=1  raw='Rating: 1'
[1142312780] pred=1  raw='Rating: 1'
[9007711835] pred=1  raw='Rating: 1'
[7660965032] pred=2  raw='Rating: 2'
[4490238304] pred=2  raw='Rating: 2'
[6700091934] pred=4  raw='Rating: 4'
[8859378993] pred=4  raw='Rating: 4'
[5385580298] pred=5  raw='Rating: 5'
[8026758110] pred=5  raw='Rating: 5'
[6891429025] pred=4  raw='Rating: 4'
[8284316162] pred=4  raw='Rating: 4'
[5157844844] pred=1  raw='Rating: 1'
[2362456901] pred=2  raw='Rating: 2'
[1192841122] pred=3  raw='Rating: 3'
[1828515736] pred=4  raw='Rating: 4'
[7108069930] pred=1  raw='Rating: 1'
[4057000359] pred=1  raw='Rating: 1'
[5996699478] pred=3  raw='Rating: 3'
[4954980874] pred=3  raw='Rating: 3'
[6108122488] pred=5  raw='Rating: 5'
[6828515473] pred=1  raw='Rating: 1'
[9685531933] pred=2  raw='Rating: 2'
[5234576402] pred=1  raw='Rating: 1'
[8617590587] pred=1  raw='Rating: 1'
[6333727735] pred=1  raw='Rating: 1'
[5386836225] pred=5  raw='Rating: 5'
[1991726581] pred=1  raw='Rating: 1'
[9588094063] pred=5  raw='Rating: 5'
[4698377831] pred=4  raw='Rating: 4'
[5546696447] pred=1  raw='Rating: 1'
[5931976339] pred=1  raw='Rating: 1'
[6335177391] pred=2  raw='Rating: 2'
[7752913183] pred=2  raw='Rating: 2'
[6322907706] pred=4  raw='Rating: 4'
[4823689999] pred=5  raw='Rating: 5'
[3344317399] pred=1  raw='Rating: 1'
[8580159762] pred=2  raw='Rating: 2'
[7053281528] pred=4  raw='Rating: 4'
[3631158848] pred=5  raw='Rating: 5'
[7856599481] pred=1  raw='Rating: 1'
[8872894184] pred=5  raw='Rating: 5'
[3212458644] pred=5  raw='Rating: 5'
[3595956324] pred=1  raw='Rating: 1'
[2721135065] pred=2  raw='Rating: 2'
[4532385362] pred=2  raw='Rating: 2'
[8212779188] pred=3  raw='Rating: 3'
[1527441241] pred=5  raw='Rating: 5'
[7684224591] pred=4  raw='Rating: 4'
[1934883311] pred=5  raw='Rating: 5'
[3445443894] pred=2  raw='Rating: 2'
[8386505012] pred=1  raw='Rating: 1'
[3238295133] pred=3  raw='Rating: 3'
[7953676869] pred=2  raw='Rating: 2'
[6282791131] pred=1  raw='Rating: 1'
[8952034624] pred=2  raw='Rating: 2'
[6784670181] pred=3  raw='Rating: 3'
[3605413866] pred=4  raw='Rating: 4'
[2996617673] pred=2  raw='Rating: 2'
[8299178271] pred=2  raw='Rating: 2'
[6649856797] pred=1  raw='Rating: 1'
[1683087480] pred=1  raw='Rating: 1'
[7566362975] pred=4  raw='Rating: 4'
[6686678229] pred=1  raw='Rating: 1'
[2720227484] pred=5  raw='Rating: 5'
[5039690279] pred=1  raw='Rating: 1'
[2487126900] pred=1  raw='Rating: 1'
[2288379561] pred=1  raw='Rating: 1'
[3452247467] pred=1  raw='Rating: 1'
[7217256745] pred=3  raw='Rating: 3'
[6377476182] pred=4  raw='Rating: 4'
[1913415850] pred=2  raw='Rating: 2'
[9853238440] pred=4  raw='Rating: 4'
[8114257774] pred=1  raw='Rating: 1'
[6322861397] pred=4  raw='Rating: 4'
[8000592115] pred=2  raw='Rating: 2'
[7529225350] pred=2  raw='Rating: 2'
[6522654613] pred=2  raw='Rating: 2'
[8726234163] pred=5  raw='Rating: 5'
[8674256614] pred=1  raw='Rating: 1'
[3337151448] pred=1  raw='Rating: 1'
[9379657901] pred=2  raw='Rating: 2'
[5387977464] pred=4  raw='Rating: 4'
[2159738021] pred=4  raw='Rating: 4'
[4122041752] pred=5  raw='Rating: 5'
[3854780772] pred=1  raw='Rating: 1'
[6767037387] pred=2  raw='Rating: 2'
[2961576525] pred=4  raw='Rating: 4'
[2649276596] pred=3  raw='Rating: 3'
[8467681129] pred=2  raw='Rating: 2'
[8354348912] pred=5  raw='Rating: 5'
[5475208300] pred=3  raw='Rating: 3'
[6017630194] pred=5  raw='Rating: 5'
[9100041657] pred=1  raw='Rating: 1'
[7709642634] pred=1  raw='Rating: 1'
[9751973156] pred=5  raw='Rating: 5'
[8464619449] pred=1  raw='Rating: 1'
[6966597883] pred=4  raw='Rating: 4'
[7385871123] pred=1  raw='Rating: 1'
[6021043389] pred=5  raw='Rating: 5'
[8023691814] pred=2  raw='Rating: 2'
[6330534057] pred=5  raw='Rating: 5'
[6936251435] pred=1  raw='Rating: 1'
[2368096737] pred=4  raw='Rating: 4'
[4618629420] pred=1  raw='Rating: 1'
[8956915458] pred=5  raw='Rating: 5'
[3310231174] pred=4  raw='Rating: 4'
[2435582314] pred=2  raw='Rating: 2'
[2522850171] pred=4  raw='Rating: 4'
[4509625585] pred=1  raw='Rating: 1'
[7456259051] pred=1  raw='Rating: 1'
[5067217997] pred=1  raw='Rating: 1'
[1605943828] pred=5  raw='Rating: 5'
[6989676793] pred=1  raw='Rating: 1'
[6740408337] pred=3  raw='Rating: 3'
[1868003778] pred=5  raw='Rating: 5'
[2914243004] pred=5  raw='Rating: 5'
[9794042274] pred=2  raw='Rating: 2'
[1833143787] pred=5  raw='Rating: 5'
[8380755151] pred=2  raw='Rating: 2'
[8275740123] pred=2  raw='Rating: 2'
[2064521653] pred=1  raw='Rating: 1'
[7200875976] pred=1  raw='Rating: 1'
[7978189775] pred=1  raw='Rating: 1'
[3941287575] pred=3  raw='Rating: 3'
[1204171879] pred=2  raw='Rating: 2'
[4479351330] pred=1  raw='Rating: 1'
[2427307803] pred=1  raw='Rating: 1'
[8973687693] pred=1  raw='Rating: 1'
[8977382015] pred=4  raw='Rating: 4'
[7855042290] pred=1  raw='Rating: 1'
[9062490373] pred=1  raw='Rating: 1'
[1565417935] pred=2  raw='Rating: 2'
[1061628827] pred=5  raw='Rating: 5'
[2310457897] pred=2  raw='Rating: 2'
[2833279973] pred=5  raw='Rating: 5'
[8734960449] pred=1  raw='Rating: 1'
[6971949342] pred=4  raw='Rating: 4'
[1038365379] pred=2  raw='Rating: 2'
[6738431558] pred=3  raw='Rating: 3'
[9176156591] pred=5  raw='Rating: 5'
[2041862433] pred=1  raw='Rating: 1'
[2554526280] pred=1  raw='Rating: 1'
[8592207932] pred=1  raw='Rating: 1'
[1299652759] pred=2  raw='Rating: 2'
[2367342899] pred=5  raw='Rating: 5'
[7325956316] pred=1  raw='Rating: 1'
[3587836749] pred=1  raw='Rating: 1'
[8059431030] pred=1  raw='Rating: 1'
[1144275503] pred=4  raw='Rating: 4'
[5266504801] pred=2  raw='Rating: 2'
[2666899470] pred=4  raw='Rating: 4'
[4232578933] pred=2  raw='Rating: 2'
[5236688450] pred=2  raw='Rating: 2'
[7794739330] pred=1  raw='Rating: 1'
[5915988392] pred=1  raw='Rating: 1'
[6631174288] pred=3  raw='Rating: 3'
[2838437312] pred=1  raw='Rating: 1'
[8256015486] pred=5  raw='Rating: 5'
[1894103408] pred=1  raw='Rating: 1'
[5686831632] pred=1  raw='Rating: 1'
[7702918172] pred=1  raw='Rating: 1'
[3334837465] pred=3  raw='Rating: 3'
[4754215786] pred=2  raw='Rating: 2'
[3801557887] pred=2  raw='Rating: 2'
[9283015707] pred=1  raw='Rating: 1'
[7618155595] pred=1  raw='Rating: 1'
[9950107372] pred=5  raw='Rating: 5'
[6848356387] pred=5  raw='Rating: 5'
[6295603113] pred=1  raw='Rating: 1'
[3728688399] pred=1  raw='Rating: 1'
[4236358865] pred=4  raw='Rating: 4'
[6434034204] pred=3  raw='Rating: 3'
[8319417633] pred=2  raw='Rating: 2'
[2446755279] pred=5  raw='Rating: 5'
[6819166044] pred=5  raw='Rating: 5'
[2786314369] pred=1  raw='Rating: 1'
[7570115861] pred=1  raw='Rating: 1'
[5629987266] pred=1  raw='Rating: 1'
[2914455302] pred=1  raw='Rating: 1'
[2787704621] pred=4  raw='Rating: 4'
[9711470872] pred=2  raw='Rating: 2'
[6622742407] pred=5  raw='Rating: 5'
[8887971802] pred=1  raw='Rating: 1'
[3654673914] pred=5  raw='Rating: 5'
[7680457545] pred=1  raw='Rating: 1'
[7983796156] pred=1  raw='Rating: 1'
[3682789619] pred=2  raw='Rating: 2'
[8886907039] pred=1  raw='Rating: 1'
[5288447761] pred=2  raw='Rating: 2'
[5050428888] pred=5  raw='Rating: 5'
[8217505007] pred=1  raw='Rating: 1'
[1035213043] pred=1  raw='Rating: 1'
[2932480960] pred=2  raw='Rating: 2'
[1418286431] pred=2  raw='Rating: 2'
[2344790813] pred=1  raw='Rating: 1'
[9900147421] pred=1  raw='Rating: 1'
[1450331304] pred=1  raw='Rating: 1'
[9795183989] pred=5  raw='Rating: 5'
[1127455305] pred=2  raw='Rating: 2'
[1947636216] pred=2  raw='Rating: 2'
[9844351170] pred=1  raw='Rating: 1'
[3805931037] pred=2  raw='Rating: 2'
[7540461886] pred=1  raw='Rating: 1'
[9387735416] pred=5  raw='Rating: 5'
[8285851904] pred=1  raw='Rating: 1'
[6031241896] pred=2  raw='Rating: 2'
[3521304110] pred=1  raw='Rating: 1'
[8648427686] pred=1  raw='Rating: 1'
[4830330207] pred=1  raw='Rating: 1'
[1356086874] pred=1  raw='Rating: 1'
[7635835659] pred=5  raw='Rating: 5'
[4138310346] pred=2  raw='Rating: 2'
[1418324779] pred=1  raw='Rating: 1'
[2969065043] pred=3  raw='Rating: 3'
[3291931950] pred=1  raw='Rating: 1'
[4068544565] pred=4  raw='Rating: 4'
[1816290891] pred=5  raw='Rating: 5'
[2429679832] pred=5  raw='Rating: 5'
[9742241368] pred=1  raw='Rating: 1'
[9412589523] pred=1  raw='Rating: 1'
[4578561459] pred=1  raw='Rating: 1'
[3731621113] pred=4  raw='Rating: 4'
[7190593135] pred=5  raw='Rating: 5'
[7908766051] pred=1  raw='Rating: 1'
[1933464594] pred=1  raw='Rating: 1'
[7408206603] pred=1  raw='Rating: 1'
[8674988457] pred=1  raw='Rating: 1'